spring:
  application:
    name: OpenSSUpot
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        use_sql_comments: true
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload:
    path: /Users/kwon-yejin/Downloads/
  web:
    path: http://localhost:8080/files/
  default-imag-name:
    organization: default_organization.png

token:
  jwt:
    access-key: ThisIsLocalAccessKeyThisIsLocalAccessKey
    refresh-key: ThisIsLocalRefreshKeyThisIsLocalRefreshKey
    access-expired-hours: 1 # 1시간
    refresh-expired-hours: 336  # 14일
